name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Lint
        run: |
          go get -u golang.org/x/lint/golint
          ~/go/bin/golint -set_exit_status ./...
